#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          bbremoted
# Required-Start:    $all 
# Required-Stop:     $remote_fs $syslog $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       Automatically run bbremote at boot
#                    Just change the token
### END INIT INFO

# Author: Simone Genovese <simone.genovese@icloud.com>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

DAEMON_OPTS="--token=<yourTokenHere>"

# This next line determines what user the script runs as.
DAEMON_NAME="bbremote"
DESC="BBREMOTE" 
DAEMON=/home/pi/BBRemote/bbremote
PIDFILE=/tmp/bbremote.pid

do_start () {
    sleep 10
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec /bin/bash -- -c "$DAEMON $DAEMON_OPTS > /var/log/bbremote.log 2>&1" 
}

do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
